### ISSUE TITLE
Epub output

### ISSUE THREAD

**Issue by mxstbr** [deobald/vipassana-for-hackers#1]
I'd love to have a `.epub` version of this to put on my Kindle!

**Comment by ghost** [comment]
Seconded.

**Comment by ghost** [comment]
This [program](https://calibre-ebook.com/) converts pdf's to epub

**Comment by machawk1** [comment]
@mxstbr [Here](https://github.com/machawk1/vipassana-for-hackers/blob/master/vipassana-for-hackers.epub) is an epub version as well as the updated PDF with @sycrat and @liammonahan's pending PRs applied. The procedure to generate the epub is also documented in [my fork](https://github.com/machawk1/vipassana-for-hackers)'s [README](https://github.com/machawk1/vipassana-for-hackers/blob/master/README.md) and can probably be improved but should be replicable.

**Comment by deobald** [comment]
Thanks folks! Sorry I haven't been on top of this; this document is a work-in-progress and was published to HN without my knowledge or consent. :/

@machawk1 — what's the best approach for incorporating your fork? Should I just grab your README or would you prefer to open a specific PR?

Thanks!

**Comment by deobald** [comment]
@machawk1 It looks like you've tweaked the build to clean it up in other ways as well. I'm happy to merge a PR from you with all these changes, if you'd like. It looks like you've taken a couple large steps to bring the repo into a publicly-accessible state that I'd been putting off. ;)

**Comment by machawk1** [comment]
@deobald I created PR #4.

The epub version generated is far from perfect but a start. There are still issues there like some superfluous metadata from the LaTeX being shown and the figures with black backgrounds being very difficult to see on an e-ink display (see https://github.com/machawk1/vipassana-for-hackers/issues/1) but the result is acceptable and the content very readable.

I hope to fix these "outstanding" issues when I get the chance and hope that you will be receptive to further PRs.

**Comment by deobald** [comment]
@machawk1 Before I close this issue, I wanted to double-check with you that I'm seeing the same errors you are. `latexml` returns the following:

`Conversion complete: 9 warnings; 7 errors; 5 undefined macros[{subfigure}, \setotherlanguage, \setlist, \foreignlanguage, \setdefaultlanguage]; 3 missing files[polyglossia.sty, enumitem.sty, subcaption.sty].
`

And `latexmlpost` gives me:

```
Error:malformed:document Document fails RelaxNG validation (LaTeXML)
	Validation reports: vipassana-for-hackers.xml:0: Relax-NG validity error : Did not expect element titlepage there
	vipassana-for-hackers.xml:0: Relax-NG validity error : Element document has extra content: resource
	In Post::Document[vipassana-for-hackers.... ->validate
```

If you've resolved any of these errors, I'd love to know how. :) If this is the output you're getting (the .epub result seems readable but, like you said, with some LaTeX artifacts) I'll push up my latest changes and the gen'd PDF/epub.

Thanks!

PS: Definitely receptive to additional PRs! Sorry I was so slow with your fork; I'll try to be a bit more attentive from here on out.

**Comment by machawk1** [comment]
@deobald I am seeing the exact same errors you are -- I just re-pulled and re-tested to verify.

I have yet to have a chance to investigate how to resolve these errors but plan to do so to make the presentation of the e-pub more consistent with the PDF version compiled from the LaTeX.

**Comment by deobald** [comment]
@machawk1 Coolio. That also means there was no issue with my blind monkey copy-paste of your README instructions. 😀 Thanks again for all of this. It looks like quite a few people are served well by your epub. I'll close this issue for now; feel free to open smaller issues/PRs for future fixes.
