### ISSUE TITLE
hello.

### ISSUE THREAD

**Issue by hoebat** [deobald/vipassana-for-hackers#17]
Hey!, You're in England now?

**Comment by deobald** [comment]
hey chris! nah, i work remotely from canada. basically kicked out of india
due to covid.

how goes?

**Comment by hoebat** [comment]
Oh nice. It's good to see you back in action. I've always had been a fan of xtdb so it was a surprise to see you on the project. 
 
I'm in China right now, working on my own thing. I'll write you over email.
