### ISSUE TITLE
Double bullets in some places on Kindle

### ISSUE THREAD

**Issue by machawk1** [deobald/vipassana-for-hackers#7]
I use [Calibre](https://calibre-ebook.com/) to transfer the epub to my Kindle for ease and portability of reading. When doing so, I believe Calibre converts it to a different format (.mobi, maybe?). I am encountering an issue when with double-bullets when reading the epub version on the Kindle, as transferred by Calibre. When reading it in the software-based reader bundled with Calibre on my Mac (by double-clicking the epub once downloaded), the double bullets do not appear, which leads me to believe that they are byproducts of the conversion process.

We may also consider offering the other formats (like .mobi) to prevent these deviations.

Kindle:
![img_20180510_223802](https://user-images.githubusercontent.com/2514780/39903906-755eb102-54a3-11e8-8f7b-87aaff62ea56.jpg)

Calibre reader:
<img width="370" alt="screen shot 2018-05-10 at 10 41 23 pm" src="https://user-images.githubusercontent.com/2514780/39903924-8279f8ec-54a3-11e8-913b-fa733e7bc912.png">

**Comment by deobald** [comment]
@machawk1 Strange. When I get some time to toy with the .epub output I'll see what I can do with .mobi as well. It would also be nice to fix that alignment one day. :)

**Comment by harshvardhaniimi** [comment]
Now, [Kindle](https://www.reddit.com/r/kindle/comments/15mhj5g/kindle_epub_support/) supports EPUB and has deprecated MOBI. The EPUB on the website works great.

P.S. I stumbled on the book and then eventually your blog. Great writing. (— From a fellow Vipassana meditator who just started the journey.)

**Comment by deobald** [comment]
Thanks for your kind words, @harshvardhaniimi !  It's a relief to hear that Kindle finally supports epub. As a result, I am going to close this ticket... I don't think there will ever be reason or motivation to support Mobi.

Best of luck with your practice!
